[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "my_package"
authors = [
    {name = "Chris Fritz", email = "fritz17236@htomail.com"},
]
description = "Untitled"
requires-python = ">=3.11, <3.12"
version = "0.0.1"

dependencies = [
    "numpy",
    "numba",
    "matplotlib",
    "jupyter",
    "scipy",
    "scikit-learn",
    "pydantic",
    "cupy",
    "tqdm",
    "dask",
    "dask-ml",
    "skorch",
    "dask[distributed]",
    "torchvision",
    "torch",
    "bokeh>=3.8.2",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "autoflake",
    "pytest",
]
